baseURL = 'strikewef.org'
languageCode = 'de-de'
title = 'Strike WEF'
theme = 'mainroad'
defaultContentLanguage = 'de'
defaultContentLanguageInSubdir = true

[Params]
	description = "Webseite von Strike WEF - Winterwanderung gegen das WEF nach Davos" # Site description. Used in meta description
	pager = true
	toc = true # Enable Table of Contents

[Params.style.vars]
  highlightColor = "#9d7ad2"
  fontFamilyPrimary = "'Helvetica'"

[Params.logo]
  image = "img/logo-vio.svg" # Logo image. Path relative to "static"
 

[Params.sidebar]
	home = "right"

	widgets = ["social", "languages"]

[Params.widgets.social]
	cached = false

	instagram = "strike.wef"
	telegram = "+2TxRe_-qBFE3MGFk"
	email = "strike.wef@posteo.de"

[languages]
  [languages.de]
    contentDir = 'content/de'
    disabled = false
    languageCode = 'de-DE'
    languageDirection = 'ltr'
    languageName = 'Deutsch'
    title = 'Strike WEF'
    weight = 1
    [languages.de.params]
      subtitle = '18. - 19. Januar 2025'
  [languages.en]
    contentDir = 'content/en'
    disabled = false
    languageCode = 'en-US'
    languageDirection = 'ltr'
    languageName = 'English'
    title = 'Strike WEF'
    weight = 2
    [languages.en.params]
      subtitle = '18. - 19. January 2025'
  [languages.fr]
    contentDir = 'content/fr'
    disabled = false
    languageCode = 'fr-FR'
    languageDirection = 'ltr'
    languageName = 'Fran√ßais'
    title = 'Strike WEF'
    weight = 3
    [languages.fr.params]
      subtitle = '18. . 19. Janvier 2025'
