baseURL = 'strikewef.org'
languageCode = 'de-de'
title = 'Strike WEF'
theme = 'roadster'
defaultContentLanguage = 'de'
defaultContentLanguageInSubdir = true

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[Params]
	description = "Webseite von Strike WEF - Winterwanderung gegen das WEF nach Davos" # Site description. Used in meta description
	pager = true
	toc = true # Enable Table of Contents
	
[Params.style.vars]
  highlightColor = "#6b5600"
  fontFamilyPrimary = "'Helvetica'"
  
[Params.logo]
  image = "img/logo-yellow.svg" # Logo image. Path relative to "static"

[Params.sidebar]
	home = "right"
	widgets = ["social", "languages"]
	
[Params.widgets.social]
	cached = false
	instagram = "strike.wef"
	telegram = "+2TxRe_-qBFE3MGFk"
	email = "strike.wef@posteo.de"
	mastodon = "@strikewef"
 
	
[Params.widgets.languages]
  cached = true
  
[languages]
  [languages.de]
    contentDir = 'content/de'
    disabled = false
    languageCode = 'de-DE'
    languageDirection = 'ltr'
    languageName = 'Deutsch'
    title = 'Strike WEF'
    weight = 1
    [languages.de.params]
      subtitle = '17. - 18. Januar 2026'
  [languages.en]
    contentDir = 'content/en'
    disabled = false
    languageCode = 'en-US'
    languageDirection = 'ltr'
    languageName = 'English'
    title = 'Strike WEF'
    weight = 2
    [languages.en.params]
      subtitle = '17. - 18. January 2026'
  [languages.fr]
    contentDir = 'content/fr'
    disabled = false
    languageCode = 'fr-FR'
    languageDirection = 'ltr'
    languageName = 'Fran√ßais'
    title = 'Strike WEF'
    weight = 3
    [languages.fr.params]
      subtitle = '17. - 18. Janvier 2026'

